### ISSUE TITLE
Vb.net Code

### ISSUE THREAD

**Issue by totti240282** [elebetsamer/bootstrap-snippets-visual-studio#1]
you can have this plugin for Vb.net ?

Thanks.

**Comment by elebetsamer** [comment]
The snippets are for html. The visual studio project is just to package it up. There isn't actually any c# code involved. Maybe you can give me some more context of what you are trying to accomplish?

**Comment by totti240282** [comment]
Hello and thank you for your response.
I want to use this plugin with visual studio and vb.net
