### ISSUE TITLE
Differences between codeplex and github version

### ISSUE THREAD

**Issue by ghost** [elebetsamer/bootstrap-snippets-visual-studio#3]
Hi

I see there are more files on the github version ( modal-sm.snippet, modal-lg.snippet ) then the version downloaded through the visual studio gallery. Is there any way to get these extras as a vsix somehow. Besides downloading these files and then adding them to the extension already installed? Maybe through powershell or something ? I'm kinda new to all this

**Comment by AsisttInfoTech** [comment]
Hi 4tron

First of All i must say : I'm not a contributor of / developer of this project.

Check this link ( Photo of the project on VS Gallery)  please http://visualstudiogallery.msdn.microsoft.com/site/view/file/135903/1/screenshot.png

You'll see Location of snippets and also you' ll see the "Add" button buttom-left of the dialog ;) 
Hope it helps

**Comment by ghost** [comment]
Hey @AsisttInfoTech thanks for the reply. 

So with those options , I first download the files I want from github. Namely modal-sm.snippet, modal-lg.snippet, and then add them from that Dialog? That seems fairly simply. 

Is there not easier way though? With something like nuget? Would be nice to be able to get the latest working copy the same way we add packages from nuget. Something like

PM> update-extension vs-bootstrapsnippets.

**Comment by AsisttInfoTech** [comment]
Hi 4tron,

Yeah we can say so..

For an update extension or updated nu-pack, i believe Developers will do something as soon as possible ;)

**Comment by elebetsamer** [comment]
I'm looking in to this problem now. I can see there are actually 3 missing snippets as of right now: form-group-select; modal-lg and modal-sm. I'm not sure why they are missing, but for some reason Visual Studio isn't adding them to the vsix package. Hopefully I can figure out why and release an update to the extension today.

**Comment by elebetsamer** [comment]
Just found the issue, I forgot to mark those additional snippets for inclusion in the vsix file. This is fixed in version 1.0.9 and should be available shortly.
