### ISSUE TITLE
Bootstrap 3.x prefix

### ISSUE THREAD

**Issue by ghost** [elebetsamer/bootstrap-snippets-visual-studio#4]
Is the "Bootstrap 3.x" prefix for every snippet necessary? Now instead of typing `bo<tab> al<tab>` to get the alert snippet, I have to type `bo<tab> bootstrap 3.x al<tab>`. This is at least true for VS 2015 RC, but in case this Intellisense behavior will be fixed, I think stripping it away would improve visual clarity anyway.

**Comment by elebetsamer** [comment]
Yeah, I'd be open to making this change. I haven't played around much with Visual Studio 2015 yet. I'll take a look at this once I get Visual Studio 2015 up and running.

**Comment by elebetsamer** [comment]
The Bootstrap 3.x prefix has been removed in version 1.0.11
